Friends/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.login.urls', namespace='login')),
    url(r'^friends/', include('apps.friends.urls', namespace='friends'))
]

apps/friends/urls.py
from django.conf.urls import url
from . import views           # This line is new!
urlpatterns = [   # This line has changed!
    url(r'^$', views.index, name='index'),
    url(r'^show/(?P<id>\d+)$', views.show, name ='show'),
    url(r'^add/(?P<id>\d+)$',views.add, name="add"),
    url(r'^remove/(?P<id>\d+)$',views.remove, name="remove")
    ]

apps/login/urls.py
from django.conf.urls import url
from . import views           # This line is new!
urlpatterns = [
    url(r'^$', views.index, name ='home'),     # This line has changed!
    url(r'^login/$', views.login),
    url(r'^register/$', views.register),
    url(r'^success$',views.success)
    ]

apps/friends/models.py
from django.db import models
import re, bcrypt
import time

# Create your models here.

apps/login/models.py
from django.db import models
import re, bcrypt

# Create your models here.
class UserManager(models.Manager):
    def validate_user_r(self,post_data):
        response_to_views ={}
        TheUser=User.objects.filter(email=post_data['email'])
        if TheUser:
            response_to_views['status']=False
            response_to_views['errors']={'user':"Username alredy exists"}
            return response_to_views
        errors={}
        name_Match=re.compile(r'^[a-zA-Z ]{3,255}$')
        input_valid=True
        if not re.match(name_Match, post_data['name']) or not re.match(name_Match, post_data['alias']):
            input_valid=False
            errors["alias"] = "name and alias should be more than 2 characters."
        if len(post_data['p'])<8 or post_data['p']!= post_data['cp']:
            input_valid=False
            errors['pass'] = "Password must be at least 8 characters and must match."
        response_to_views['errors']=errors
        if input_valid:
            print('got here')
            new_user = self.create(
            name=post_data['name'],
            alias=post_data['alias'],
            email=post_data['email'],
            password=bcrypt.hashpw(post_data['p'].encode(), bcrypt.gensalt())
            )
            response_to_views['status']=True
            response_to_views['id']=new_user.id
            return response_to_views
        response_to_views['status']=False
        return response_to_views
    def validate_user_l(self, post_data):
        response_to_views={}
        TheUser=self.filter(email=post_data['lemail'])
        errors={}
        if TheUser:
            if bcrypt.checkpw(post_data['lp'].encode(), TheUser[0].password.encode()):
                response_to_views['status']=True
                response_to_views['id']=TheUser[0].id
                return response_to_views
            errors['password']="Invalud password for user."
        errors['user']="User does not exist."
        response_to_views['errors']=errors
        response_to_views['status']=False
        return response_to_views

class User(models.Model):
    alias = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    email= models.EmailField(max_length=255, unique=True)
    password= models.CharField(max_length=255)
    mapping=models.ManyToManyField('self', related_name='friends')
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    objects = UserManager()

apps/friends/views.py
from django.shortcuts import render, redirect, HttpResponse
from ..login.models import User
def index(request):
    if not 'user_id' in request.session:
        return redirect("login:index")
    logged_user=User.objects.get(id=request.session['user_id'])
    context={
    'friends':User.objects.filter(mapping=logged_user),
    'notfriends':User.objects.exclude(mapping=logged_user).exclude(id=request.session['user_id'])
        }
    return render(request, 'friends/index.html', context)
def show(request, id):
    if not 'user_id' in request.session:
        return redirect("login:index")
    context={
        'alias':User.objects.get(id=id).alias,
        'name':User.objects.get(id=id).name,
        'email':User.objects.get(id=id).email,
        }
    return render(request, 'friends/show.html', context)
def add(request, id):
    if not 'user_id' in request.session:
        return redirect("login:index")
    User.objects.get(id=request.session['user_id']).mapping.add(User.objects.get(id=id))
    return redirect('friends:index')
def remove(request, id):
    if not 'user_id' in request.session:
        return redirect("login:index")
    User.objects.get(id=request.session['user_id']).mapping.remove(User.objects.get(id=id))
    return redirect('friends:index')

apps/login/views.py
from django.shortcuts import render, redirect
from .models import User
from django.contrib import messages
# Create your views here.
def index(request):

    return render(request, "login/index.html")
def register(request):
    if request.method!='POST':
        return redirect('/')
    response_from_model=User.objects.validate_user_r(request.POST)
    if response_from_model['status']:
        request.session['user_id']=response_from_model['id']
        return redirect('/success')
    for error, content in response_from_model['errors'].items():
        messages.error(request, content, extra_tags=error)
    return redirect('/')
def login(request):
    if request.method!='POST':
        return redirect('/')
    response_from_model=User.objects.validate_user_l(request.POST)
    if response_from_model['status']:
        request.session['user_id']=response_from_model['id']
        return redirect('/success')
    for error, content in response_from_model['errors'].items():
        messages.error(request, content, extra_tags=error)
    return redirect('/')
def success(request):
    if 'user_id' in request.session:
        return redirect('friends:index')
    return redirect('/')

apps/friends/templates/friends/index.html
<!DOCTYPE html>
<html lang='en'>
  <head>
    <meta charset="utf-8">
    <title>Friends</title>
  </head>
  <body>
    <h4><a href={% url 'login:home' %}>Logout</a></h4>

    <table>

      <h3>Your Friends</h3>
      <tr>
        <th>Alias </th>
        <th> Action </th>
      </tr>
      {%for friend in friends%}
        <tr>
          <td>{{friend.name}}</td>
          <td><a href= "{% url 'friends:show' id=friend.id  %}" method="post">View Friend</a></td>
          <td><a href= "{% url 'friends:remove' id=friend.id  %}" method="post">Remove Friend</a></td>
      {%endfor%}
      </tr>
    </table>
    <table>
      <h3>friends planned by other users</h3>
      <tr>
        <th>Item</th>
        <th>Added_By</th>
        <th>Date_Added</th>
        <th>Action</th>
      </tr>
      {%for friend in notfriends%}
        <tr>
          <td><a href={% url 'friends:show' id=friend.id %} method = "post">{{friend.name}}</a></td>
          <td><a href={% url 'friends:add' id=friend.id  %} method="post">Add as Friend</a></td>
      {%endfor%}
      </tr>
    </table>
  </body>
</html>

apps/friends/templates/friends/show.html
<!DOCTYPE html>
<html lang='en'>
  <head>
    <meta charset="utf-8">
    <title>Profile</title>
  </head>
  <body>
    <h4><a href= "{% url 'login:home' %}" >Logout</a></h4>
    <h3>{{alias}}'s Profile'</h3>
    <h3>name: {{name}}</h3>
    <h4>email: {{email}}</h4>
  </body>
</html>

apps/login/templates/login/index.html
<!DOCTYPE html>
<html lang='en'>
  <head>
    <meta charset="utf-8">
    <title>Login and Registration</title>
  </head>
  <body>
    <div>
      {%for message in messages%}
        <p>{{message}}</p>
      {%endfor%}
    </div>
    <table>
      <form class="" action="register/" method="post">
        {%csrf_token%}
        <tr>
          <td>Registration</td>
        </tr>
        <tr>
          <td>Name: </td>
          <td><input type="text" name="name" value=""></td>
        </tr>
        <tr>
          <td>Email: </td>
          <td><input type="text" name="email" value=""></td>
        </tr>
        <tr>
          <td>Alias: </td>
          <td><input type="text" name="alias" value=""></td>
        </tr>
        <tr>
          <p>*pass should contain at least 8 characters.</p>
        </tr>
        <tr>
          <td>Password: </td>
          <td><input type="password" name="p" value=""></td>
        </tr>
        <tr>
          <td>confirm pw: </td>
          <td><input type="password" name="cp" value=""></td>
        </tr>
        <tr>
        <td><input type="submit" value="Register"></td>
        </tr>
      </form>
    </table>
    <table>
      <form class="" action="login/" method="post">
        {%csrf_token%}
        <tr>
          <td>Login</td>
        </tr>
        <tr>
          <td>email: </td>
          <td><input type="text" name="lemail" value=""></td>
        </tr>
        <tr>
          <td>Password: </td>
          <td><input type="password" name="lp" value=""></td>
        </tr>
        <tr>
          <td><input type="submit" name="" value="Login"></td>
        </tr>
      </form>
    </table>
  </body>
</html>